additionalTrustBundlePolicy: Proxyonly
apiVersion: v1
baseDomain: $BASE_DOMAIN
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: 
    aws:
      rootVolume:
        iops: 2000
        size: 500
        type: io1 
      metadataService:
        authentication: Optional 
      type: c5.4xlarge
      zones:
      - ${REGION}a
      - ${REGION}b
      - ${REGION}c
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    aws:
      zones:
      - ${REGION}a
      - ${REGION}b
      - ${REGION}c
      rootVolume:
        iops: 4000
        size: 500
        type: io1 
      metadataService:
        authentication: Optional 
      type: m6i.xlarge
  replicas: 3
metadata:
  creationTimestamp: null
  name: $CLUSTER_NAME 
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 172.18.0.0/16
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region:          $REGION
    userTags:
      adminContact:  jaradtke@amazon.com
      costCenter:    8675309
      purpose:       'IPI Installation Testing'
      fips:          false
      jokes:         dad
      notes:         'Testing extensible tagging'
fips: false
publish: External
pullSecret: '$PULL_SECRET'
sshKey: '$SSH_KEY'
